{
 "title": "Number of trucks. per project per day",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project_name",
    "query": "SELECT DISTINCT project_name\nFROM tickets\nWHERE ticket_status NOT IN ('NOT_STARTED', 'CANCELLED')\nORDER BY project_name;\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Aggregate data by day per project. (Yearly report)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "etl_db",
     "rawSql": "SELECT\r\n    TO_CHAR(sub.month_start, 'Mon') AS month,\r\n    sub.project_name,\r\n    SUM(sub.truck_count) AS total_truck_allocation,\r\n    SUM(sub.trucks_allocated) AS total_trucks_allocated\r\nFROM (\r\n    SELECT\r\n        j.project_name,\r\n        tc.count AS truck_count,\r\n        tc.allocated AS trucks_allocated,\r\n        DATE_TRUNC('month', TO_TIMESTAMP(j.createdAt / 1000)) AS month_start\r\n    FROM jobs j\r\n    JOIN job_truck_categories tc\r\n        ON j.job_id = tc.job_id\r\n    WHERE\r\n        TO_TIMESTAMP(j.createdAt / 1000)::date >= DATE_TRUNC('year', CURRENT_DATE)\r\n        AND (\r\n            '$project_name' = 'All'\r\n            OR j.project_name ILIKE '%' || '$project_name' || '%'\r\n        )\r\n) sub\r\nGROUP BY sub.month_start, sub.project_name\r\nORDER BY sub.month_start, sub.project_name;\r\n"
    },
    {
     "dataset": "etl_db",
     "rawSql": "SELECT\r\n    to_char(to_timestamp(j.createdAt / 1000), 'YYYY-MM-DD') AS day,\r\n    j.project_name,\r\n    SUM(tc.count) AS total_truck_allocation,\r\n    SUM(tc.allocated) AS total_trucks_allocated\r\nFROM jobs j\r\nJOIN job_truck_categories tc\r\n    ON j.job_id = tc.job_id\r\nWHERE to_timestamp(j.createdAt / 1000)::date >= CURRENT_DATE - INTERVAL '30 days'\r\nGROUP BY day, j.project_name\r\nORDER BY day, j.project_name;\r\n"
    }
   ]
  },
  {
   "title": "Daily Truck Allocation by Project and Job without filte.",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "etl_db",
     "rawSql": "SELECT DISTINCT\r\n    j.project_name,\r\n    j.name AS job_name,\r\n    tc.name AS truck_category,\r\n    tc.count AS truck_count,\r\n    tc.allocated AS trucks_allocated\r\nFROM jobs j\r\nJOIN job_truck_categories tc\r\n    ON j.job_id = tc.job_id\r\nWHERE to_timestamp(j.createdAt / 1000)::date = CURRENT_DATE\r\nORDER BY j.project_name, j.name, tc.name;\r\n"
    }
   ]
  },
  {
   "title": "Weekly Report (current week, Monday–Sunday) without filter.",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "etl_db",
     "rawSql": "SELECT DISTINCT\r\n    j.project_name,\r\n    j.name AS job_name,\r\n    tc.name AS truck_category,\r\n    tc.count AS truck_count,\r\n    tc.allocated AS trucks_allocated\r\nFROM jobs j\r\nJOIN job_truck_categories tc\r\n    ON j.job_id = tc.job_id\r\nWHERE to_timestamp(j.createdAt / 1000)::date >= date_trunc('week', CURRENT_DATE)\r\nORDER BY j.project_name, j.name, tc.name;"
    }
   ]
  },
  {
   "title": "Monthly Report (grouped by Current month, e.g., Oct, Sep…) without filter. ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "etl_db",
     "rawSql": "SELECT DISTINCT\r\n    to_char(to_timestamp(j.createdAt / 1000), 'YYYY-MM-DD') AS job_date,\r\n    j.project_name,\r\n    j.name AS job_name,\r\n    tc.name AS truck_category,\r\n    tc.count AS truck_count,\r\n    tc.allocated AS trucks_allocated\r\nFROM jobs j\r\nJOIN job_truck_categories tc\r\n    ON j.job_id = tc.job_id\r\nWHERE to_timestamp(j.createdAt / 1000)::date >= date_trunc('month', CURRENT_DATE)\r\nORDER BY job_date, j.project_name, j.name, tc.name;\r\n"
    }
   ]
  }
 ]
}